apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: kitapkurdu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: sayinmehmet47/backend-kitapkurdu-1:latest
          env:
            - name: MONGO_URI
              value: '***'
            - name: JWT_SECRET
              value: 'fsafdafdasfdk'
            - name: PORT
              value: '5000'
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: kitapkurdu
spec:
  selector:
    app: backend
  ports:
    - name: backend
      protocol: TCP
      port: 5000
      targetPort: 5000
