apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: kitapkurdu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kitapkurdu
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: kitapkurdu
        tier: backend
        track: stable
    spec:
      containers:
        - name: kitapkurdu
          image: latifyildirim/kitapkurdu-backend:latest
          env:
            - name: MONGO_URI
              value: '***'
            - name: JWT_SECRET
              value: 'fsafdafdasfdk'
            - name: PORT
              value: '5000'
          ports:
            - containerPort: 5000
          resources:
      restartPolicy: Always
--- 
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: kitapkurdu
spec: 
  selector:
      app: kitapkurdu
      tier: backend 
  # type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000 
