apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: kitapkurdu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: sayinmehmet47/client-kitapkurdu-1:latest
          env:
            - name: REACT_APP_LOCAL_API
              value: 'http://localhost:5000'
            - name: REACT_APP_DEV_API
              value: 'https://kitapkurdu.onrender.com'
            - name: REACT_APP_PROD_API
              value: 'https://kitapkurdu.onrender.com'
            - name: REACT_APP_CLOUDINARY_URL
              value: 'https://api.cloudinary.com/v1_1/dsequsn4l/upload?upload_preset=uploads'
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: kitapkurdu
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
