name: deploy-manifests

on:
  push:
    branches:
      - master
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t sayinmehmet47/auth .

      # Set up kubectl with the Rancher kubeconfig from the GitHub secret
      - name: Configure kubectl
        run: |
          echo "$RANCHER_KUBECONFIG" > kubeconfig.yaml
          export KUBECONFIG=$PWD/kubeconfig.yaml

      # Apply your Kubernetes manifests to the Rancher cluster
      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f infra/k8s
          kubectl apply -f infra/k8s-prod
