name: deploy-manifests

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      # - run: cd auth && docker build -t sayinmehmet47/auth .

      # # Set up kubectl with the Rancher kubeconfig from the GitHub secret
      # - name: Configure kubectl
      #   run: |
      #     echo "$RANCHER_KUBECONFIG" > kubeconfig.yaml
      #     export KUBECONFIG=$PWD/kubeconfig.yaml

      # # Apply your Kubernetes manifests to the Rancher cluster
      # - name: Apply Kubernetes manifests
      #   run: |
      #     kubectl apply -f infra/k8s
      #     kubectl apply -f infra/k8s-prod

      - name: Update Rancher deployment with new image
        env:
          RANCHER_SERVER: https://rancher.riwi.dev
          RANCHER_ACCESS_KEY: ${{ secrets.RANCHER_ACCESS_KEY }}
          RANCHER_SECRET_KEY: ${{ secrets.RANCHER_SECRET_KEY }}
          RANCHER_CLUSTER_ID: c-m-cp898j4l
          RANCHER_NAMESPACE: kitapkurdu
          RANCHER_DEPLOYMENT_NAME: frontend-deployment
          DOCKER_IMAGE: sayinmehmet47/client-kitapkurdu-1:latest
        run: |
          rancher login $RANCHER_SERVER -t $RANCHER_ACCESS_KEY -p $RANCHER_SECRET_KEY --context $RANCHER_CLUSTER_ID
          rancher kubectl set image deployment/$RANCHER_DEPLOYMENT_NAME $RANCHER_DEPLOYMENT_NAME=$DOCKER_IMAGE --namespace $RANCHER_NAMESPACE
          rancher kubectl rollout restart deployment/$RANCHER_DEPLOYMENT_NAME --namespace $RANCHER_NAMESPACE
